"""
Django settings for src project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Путь к корневой директории проекта
BASE_DIR = Path(__file__).resolve().parent.parent

# Явно загружаем файл .env из корня проекта
load_dotenv(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "0")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", True)

ALLOWED_HOSTS = [os.getenv("ALLOWED_HOST", "*")]

APP_NAME = "Unicon Project"

# Application definition

INSTALLED_APPS = [
    "modeltranslation",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "import_export",
]

# ─────────────────────────────────────────────────────────────────────────────
# MIDDLEWARE
# ИСПРАВЛЕНО: JWTAuthenticationMiddleware перемещена СТРОГО ПОСЛЕ
# django.contrib.auth.middleware.AuthenticationMiddleware.
#
# Причина: AuthenticationMiddleware безусловно перезаписывает request.user
# через SimpleLazyObject на основе Django-сессии. Раз мы больше не вызываем
# django.contrib.auth.login() (см. core/auth.py — JWT вместо сессий),
# запрос без сессии всегда получал бы request.user = AnonymousUser,
# и если бы AuthenticationMiddleware стояла ПОСЛЕ нашей JWT-мидлвари, она бы
# затирала уже корректно проставленного JWT-пользователя обратно на анонима.
#
# Теперь порядок такой: сперва AuthenticationMiddleware ставит AnonymousUser
# (т.к. сессии нет), а затем JWTAuthenticationMiddleware перезаписывает
# request.user на реального пользователя по access_token — её результат
# в цепочке последний и уже ничем не перетирается.
#
# DashboardSecurityMiddleware по-прежнему в самом конце цепочки — она
# работает уже после того, как JWT-мидлварь гарантированно проставила
# валидного request.user.
# ─────────────────────────────────────────────────────────────────────────────
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware", 
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "core.auth_jwt.middleware.JWTAuthenticationMiddleware",  # JWT-аутентификация — теперь ПОСЛЕ AuthenticationMiddleware
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.auth_jwt.middleware.DashboardSecurityMiddleware",  # защита дашборда, в конце цепочки
]

ROOT_URLCONF = "src.urls"

AUTH_USER_MODEL = "core.User"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "src.context_processors.APP_NAME",
            ],
        },
    },
]

WSGI_APPLICATION = "src.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


if DEBUG:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PASS"),
            "HOST": os.getenv("DB_HOST"),
            "PORT": os.getenv("DB_PORT"),
        }
    }


# Cache — используй REDIS_URL в продакшене, LocMemCache для локальной разработки.
# Для Redis: pip install django-redis  или  встроенный бэкенд Django ≥ 4.0
_REDIS_URL = os.getenv("REDIS_URL")
if _REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": _REDIS_URL,
            "OPTIONS": {"socket_connect_timeout": 5},
            "KEY_PREFIX": "cyb",
        }
    }
else:
    # Безопасный дефолт для разработки (хранит в памяти процесса).
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "cyb-quiz",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "ru-ru"

LANGUAGES = [
    ("uz", "Uzbek"),
    ("ru", "Russian"),
    ("en", "English"),
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

TIME_ZONE = "Asia/Tashkent"

USE_I18N = True

USE_TZ = False
    
# ─────────────────────────────────────────────────────────────────────────────
# django-modeltranslation
# uz — базовый язык: текущий контент в БД преимущественно на узбекском/
# смешанный, поэтому именно в *_uz бэкофиллим старые значения (см.
# data-миграцию 00XX_backfill_translations.py).
# ─────────────────────────────────────────────────────────────────────────────
MODELTRANSLATION_DEFAULT_LANGUAGE = 'uz'
MODELTRANSLATION_LANGUAGES = ('uz', 'ru', 'en')
MODELTRANSLATION_FALLBACK_LANGUAGES = {'default': ('uz',)}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

# Media files (docs, Images, files)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

RANGE = os.getenv("RANGE", 0)

TOKEN = os.getenv("TOKEN", 0)

# ─────────────────────────────────────────────────────────────────────────────
# JWT / Cookie-аутентификация
# Названия и TTL кук фиксированы в Shared Context и не должны меняться,
# т.к. на них завязаны middleware, Redis-ключи и логика контроллеров логина/рефреша.
# ─────────────────────────────────────────────────────────────────────────────

# Имена cookie для access и refresh токенов
JWT_ACCESS_COOKIE_NAME = "access_token"
JWT_REFRESH_COOKIE_NAME = "refresh_token"

# Время жизни токенов в секундах (TTL)
JWT_ACCESS_TOKEN_TTL = 90000        # 15 минут
JWT_REFRESH_TOKEN_TTL = 604800    # 7 дней

# Общие флаги безопасности для обеих кук (access и refresh)
JWT_COOKIE_HTTPONLY = True
JWT_COOKIE_SECURE = not DEBUG
JWT_COOKIE_SAMESITE = "Lax"

# ─────────────────────────────────────────────────────────────────────────────
# CSRF
# CSRF_COOKIE_HTTPONLY=False обязателен: фронтенд должен читать csrftoken
# из cookie через JS и передавать его в заголовке запроса.
# CSRF_COOKIE_SECURE и CSRF_COOKIE_SAMESITE выставлены так же строго, как и
# флаги JWT-кук (Secure=True, SameSite=Lax), для единой политики безопасности кук.
# Сама проверка CSRF выполняется стандартным CsrfViewMiddleware — переопределять
# его не нужно.
# ─────────────────────────────────────────────────────────────────────────────
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = "Lax"